spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
      - id: user_service
        uri: lb://USERMS
        predicates:
        - Path=/api/v1.0/users/**
      - id: user_service
        uri: lb://MAPPING-ERRORMS
        predicates:
        - Path=/api/v1.0/mappingError/**

server:
    port: 4443

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    react.netty.http.client: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://192.168.1.10:8761/eureka}
